<?php

/**
 * Implements hook_mail().
 */
function event_manager_mail($key, &$message, $params) {
  switch ($key) {

    case 'user_registration':
      $message['subject'] = t('Event Registration Confirmation');
      $message['body'][] = $params['message'];
      break;

    case 'admin_notification':
      $message['subject'] = t('New Event Registration');
      $message['body'][] = $params['message'];
      break;
  }
}
